app:
  name: user-crud-app
  resources:
    requests:
      cpu: 100m
      memory: 192Mi
    limits:
      memory: 512Mi

replicaCount: 2

existingSecret: user-crud-secrets

appImage:
  repository: user-crud-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

livenessProbe:
  httpGet:
    path: /api/health
    port: 5000

readinessProbe:
  httpGet:
    path: /api/ready
    port: 5000

dbImage:
  repository: mysql
  tag: "8.4"

db:
  name: mysql
  storage: 5Gi

service:
  port: 5000
  targetPort: 5000

config:
  dbPort: 3306
  dbName: cruddb
  dbUser: cruduser

ingress:
  className: nginx
  path: /
  host: crud.test.com
  clusterIssuer: selfsigned
  tlsSecretName: user-crud-tls
