apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.db.component }}
  ports:
    - port: {{ .Values.config.dbPort }}