apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-cm
data:
  DB_HOST: {{ .Values.db.name | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}