apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-crud-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-crud-app
  template:
    metadata:
      labels:
        app: user-crud-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: user-crud-app
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: SECRET_KEY
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
          readinessProbe:
            httpGet:
              path: /api/ready
              port: 5000
          resources:
            requests:
              cpu: 100m
              memory: 192Mi
            limits:
              memory: 512Mi