apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: {{ .Values.frontend.component }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}